name: Deploy to Server
on:
    push:
      branches:
        - dev

jobs:
    connect:
        - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            port: ${{ secrets.PORT }}
            script: whoami