name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.10'

      - name: Install Composer dependencies
        run: |
          cd ./app/bedrock
          composer install --no-dev --optimize-autoloader

      - name: Copy environment file
        run: |
          cd ./app/bedrock
          cp .env.example .env

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Yarn dependencies
        run: |
          cd ./app/bedrock/web/app/themes/sage
          yarn install

      - name: Build assets
        run: |
          cd ./app/bedrock/web/app/themes/sage
          yarn build

      - name: Create artifact
        run: |
          tar -czf artifact.tar.gz -C ./app/bedrock .

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /kunden/homepages/15/d821549628/htdocs/yuvedo-wp
            git pull origin main
            tar -xzf /path/to/artifact.tar.gz -C .
            # Add any other deployment commands here
