name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.10'

      - name: Install Composer dependencies
        run: |
          cd ./app/bedrock
          composer install --no-dev --optimize-autoloader

      - name: Copy environment file
        run: |
          cd ./app/bedrock
          cp .env.example .env

      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        with:
          path: ./app/bedrock/web/app/themes/sage/node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Yarn dependencies
        run: |
          cd ./app/bedrock/web/app/themes/sage
          yarn install

      - name: Build assets
        run: |
          cd ./app/bedrock/web/app/themes/sage
          yarn build

      - name: Create artifact
        run: |
          mkdir -p ./artifact
          tar -czf ./artifact/artifact.tar.gz -C ./app/bedrock .

      - name: Log Artifact Information
        run: |
          echo "Artifact Path: $(pwd)/artifact/artifact.tar.gz"
          echo "Artifact Size: $(du -sh ./artifact/artifact.tar.gz | awk '{print $1}')"
  
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /kunden/homepages/15/d821549628/htdocs/yuvedo-wp
            tar -xzf ./artifact/artifact.tar.gz -C .
            # Add any other deployment commands here
