name: Deploy to Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.10'

      - name: Install Composer dependencies
        run: |
          cd ./app/bedrock
          composer install --no-dev --optimize-autoloader

      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        with:
          path: ./app/bedrock/web/app/themes/yuvedo_sage_2024/node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Yarn dependencies
        run: |
          cd ./app/bedrock/web/app/themes/yuvedo_sage_2024
          yarn install

      - name: Build assets
        run: |
          cd ./app/bedrock/web/app/themes/yuvedo_sage_2024
          yarn build

      - name: Install Composer dependencies
        run: |
          cd ./app/bedrock/web/app/themes/yuvedo_sage_2024
          composer install

      - name: Create artifact
        run: |
          rm -rf ../deploy
          mkdir -p ../deploy
          cp -r ./app/bedrock/* ../deploy
          tar -czvf deploy.tar.gz -C ../deploy/ .

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "deploy.tar.gz"
          target: "yuvedo-wp/"
      
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd yuvedo-wp/
            tar -xzf deploy.tar.gz
            rm deploy.tar.gz
